# creates table 'dataset'
CREATE TABLE dataset (
	duration integer, 
	protocol varchar(10),
	service varchar(10),
	flag varchar(10),
	src_bytes integer,
	dst_bytes integer,
	land smallint,
	wrong_fragment integer,
	urgent integer,
	hot integer,
	num_failed_logins integer,
	logged_in smallint,
	num_compromised integer,
	root_shell integer,
	su_attempted integer,
	num_root integer,
	num_file_creations integer,
	num_shells integer,
	num_access_files integer,
	num_outbound_cmds integer,
	is_host_login smallint,
	is_guest_login smallint,
	count integer,
	srv_count integer,
	serror_rate real,
	srv_serror_rate real,
	rerror_rate real,
	srv_rerror_rate real,
	same_srv_rate real,
	diff_srv_rate real,
	srv_diff_host_rate real,
	classification varchar(15)
);